### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by ralrigs** [Horunkan/Sudoku#1]
Hello , is it possible to put this on the playstore for free with AD, i mean if sudoku got special right ? or if its ok to put it on playstore without usage right problem (app remove + possible account closure ...) , just with give credit to you for the developpement .
thanks

**Comment by MaciejKitowski** [comment]
Github license prohibits distribution or reproduction projects without author permission.

Sorry, but I won't give rights to my project for someone, who has only 1 action on account. By the way this game isn't ready yet to publish ;-)
