### ISSUE TITLE
Brand new to programming with a noob question

### ISSUE THREAD

**Issue by Ruetix** [Horunkan/Sudoku#3]
I am trying to use your sodoku code but when I import it then I get several errors with "interpolated strings" and "asynchronous functions". I have read that this comes from Unity not using c# 6. 

Can you give me any tips or help to either eliminate the errors or how to work in c# 6?

**Comment by MaciejKitowski** [comment]
@Ruetix Which version of Unity are you using? I'm not sure, but if I remember correctly C# 6 was added in 2017.1 version as experimental. In 2018.1 was marked as stable. So you have to use ver. 2017.1 at least.

Check your Player settings too. You should select .NET 4.x in _"Scripting Runtime Version"_ and _"Api Compablity Level"_. You can find these settings under _Edit/Project Settings/Player/Other Settings/Configuration_
![bez nazwy](https://user-images.githubusercontent.com/8428671/44871988-aea53500-ac94-11e8-9705-c3f47c5b0eaf.png)
